<?php
namespace App\Corporations\CreepyPastaMachine;

class Config
{
    
    const STATES = 12;
    const CORPORATION = 1;
	const TRANSITION_SUMMARIZER_AGENT = 1;
	const TRANSITION_PARANORMALIST_AGENT = 2;
	const TRANSITION_WRITER_AGENT = 3;
	const TRANSITION_FULLTEXT_AGENT = 10;
	const TRANSITION_FORMATTER_AGENT = 4;
	const TRANSITION_PHOTOGRAPHER_AGENT = 5;
	const TRANSITION_ASSESSOR_AGENT = 6;
	const TRANSITION_ARBITER_AGENT = 7;
	const TRANSITION_BLOGGER_AGENT = 8;
	const TRANSITION_SCPCLERK_AGENT = 9;

}