<?php
namespace App\Corporations\CreepyPastaMachine;

class Config
{
    
    const STATES = 13;
    const CORPORATION = 3;
	const TRANSITION_SUMMARIZER_AGENT = 21;
	const TRANSITION_PARANORMALIST_AGENT = 22;
	const TRANSITION_WRITER_AGENT = 23;
	const TRANSITION_FULLTEXT_AGENT = 30;
	const TRANSITION_FORMATTER_AGENT = 24;
	const TRANSITION_PHOTOGRAPHER_AGENT = 25;
	const TRANSITION_ASSESSOR_AGENT = 26;
	const TRANSITION_ARBITER_AGENT = 27;
	const TRANSITION_BLOGGER_AGENT = 28;
	const TRANSITION_SCPCLERK_AGENT = 29;

}