<?php
namespace App\Corporations\CreepyPastaMachine;

class Config
{
    
    const STATES = 13;
    const CORPORATION = 108;
	const TRANSITION_SUMMARIZER_AGENT = 517;
	const TRANSITION_PARANORMALIST_AGENT = 518;
	const TRANSITION_WRITER_AGENT = 519;
	const TRANSITION_FULLTEXT_AGENT = 526;
	const TRANSITION_FORMATTER_AGENT = 520;
	const TRANSITION_PHOTOGRAPHER_AGENT = 521;
	const TRANSITION_ASSESSOR_AGENT = 522;
	const TRANSITION_ARBITER_AGENT = 523;
	const TRANSITION_BLOGGER_AGENT = 524;
	const TRANSITION_SCPCLERK_AGENT = 525;

}